const PREFIX = "REGISTER_";

export const registerConstants = {
    REGISTER_REQUEST: `${PREFIX}REGISTER_REQUEST`,
    REGISTER_SUCCESS: `${PREFIX}REGISTER_SUCCESS`,
    REGISTER_FAILURE: `${PREFIX}REGISTER_FAILURE`,
};
