const PREFIX = "LOGIN_";

export const loginConstants = {
    LOGIN_REQUEST: `${PREFIX}LOGIN_REQUEST`,
    LOGIN_SUCCESS: `${PREFIX}LOGIN_SUCCESS`,
    LOGIN_FAILURE: `${PREFIX}LOGIN_FAILURE`,
    LOAD_USER: `${PREFIX}LOAD_USER`,
    LOGOUT: `${PREFIX}LOGOUT`,
    LOGOUT_SUCCESS: `${PREFIX}LOGOUT_SUCCESS`,
    CLEAR_ERROR: `${PREFIX}CLEAR_ERROR`,
};
