const PREFIX = "WEATHER_";

export const weatherConstants = {
    LOAD_WEATHER: `${PREFIX}LOAD_WEATHER`,
    LOAD_WEATHER_SUCCESS: `${PREFIX}LOAD_WEATHER_SUCCESS`,
    LOAD_WEATHER_ERROR: `${PREFIX}LOAD_WEATHER_ERROR`,
};
